apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stubs
    release: {{ .Release.Name }}
    app.kubernetes.io/name: stubs
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-stubs
spec:
  replicas: {{ .Values.stubs.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stubs
        release: {{ .Release.Name }}
        requires: db
        app.kubernetes.io/name: stubs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: stubs
        image: "{{ .Values.stubs.image.repository }}:{{ .Values.stubs.image.tag }}"
        imagePullPolicy: {{ .Values.stubs.image.pullPolicy }}
        env:
          - name: PORT
            value: "80"
          - name: SMARTPAY_EXPECTED_USER
            value: smartpay-user
          - name: SMARTPAY_EXPECTED_PASSWORD
            value: smartpay-password
          - name: WORLDPAY_EXPECTED_USER
            value: worldpay-user
          - name: WORLDPAY_EXPECTED_PASSWORD
            value: worldpay-password
          - name: CONNECTOR_SANDBOX_NOTIFICATION_URL
            value: http://connector/v1/api/notifications/sandbox
          - name: CONNECTOR_WORLDPAY_NOTIFICATION_URL
            value: http://connector/v1/api/notifications/worldpay 
          - name: CONNECTOR_SMARTPAY_NOTIFICATION_URL
            value: http://connector/v1/api/notifications/smartpay
          - name: CONNECTOR_EPDQ_NOTIFICATION_URL
            value: http://connector/v1/api/notifications/epdq
          - name: CONNECTOR_DIRECT_DEBIT_SANDBOX_NOTIFICATION_URL
            value: http://directdebit-connector/v1/webhooks/sandbox
          - name: CONNECTOR_DIRECT_DEBIT_GOCARDLESS_NOTIFICATION_URL
            value: http://directdebit-connector/v1/webhooks/gocardless
          - name: CONNECTOR_DIRECT_DEBIT_GOCARDLESS_WEBHOOK_SECRET
            value: supersecret
          - name: EPDQ_SHA_OUT_PASSPHRASE
            value: mysecretpassphrase
          - name: EXTERNAL_STUBS_URL
            value: http://stubs/
          - name: FRONTEND_URL
            value: http://frontend
        resources: {}
        ports:
          - name: app
            containerPort: 80
          - name: admin
            containerPort: 8081
      restartPolicy: Always
