endtoend:
  replicaCount: 1
  verbose: "true"
  image:
    repository: registry.london.portfolio.govsvc.uk/pay/endtoend
    tag: latest
    pullPolicy: IfNotPresent

demoService:
  replicaCount: 1
  image:
    repository: registry.london.portfolio.govsvc.uk/pay/demo-service
    tag: latest
    pullPolicy: IfNotPresent

postgresql:
  replicaCount: 1
  image:
    repository: postgres@sha256
    tag: 7ea445e9e8f1456ff1d27891901719d088c94e27e1d4a3d0f68c485dad5cb673
    pullPolicy: IfNotPresent

stubs:
  replicaCount: 1
  image:
    repository: registry.london.portfolio.govsvc.uk/pay/stubs
    tag: latest
    pullPolicy: IfNotPresent

selenium:
  hub:
    tag: 3.9.1-actinium
    podAnnotations:
      "sidecar.istio.io/inject": "false"
    ingress:
      hosts:
        - selenium-hub
  chrome:
    enabled: true
    replicas: 4
    podAnnotations:
      "sidecar.istio.io/inject": "false"
