apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: connector
    release: {{ .Release.Name }}
    app.kubernetes.io/name: connector
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-connector
spec:
  replicas: {{ .Values.connector.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: connector
        release: {{ .Release.Name }}
        requires: db
        app.kubernetes.io/name: connector
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        iam.amazonaws.com/role: {{ template "principal-iam-role" . }}
    spec:
      containers:
      - name: connector
        image: "{{ .Values.connector.image.repository }}:{{ .Values.connector.image.tag }}"
        imagePullPolicy: {{ .Values.connector.image.pullPolicy }}
        env:
        - name: PORT
          value: "80"
        - name: APPLE_PAY_PAYMENT_PROCESSING_CERTIFICATE
          value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVjRENDQkJhZ0F3SUJBZ0lJVXlyRU00SXpCSFF3Q2dZSUtvWkl6ajBFQXdJd2dZQXhOREF5QmdOVkJBTU0KSzBGd2NHeGxJRmR2Y214a2QybGtaU0JFWlhabGJHOXdaWElnVW1Wc1lYUnBiMjV6SUVOQklDMGdSekl4SmpBawpCZ05WQkFzTUhVRndjR3hsSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNUk13RVFZRFZRUUtEQXBCCmNIQnNaU0JKYm1NdU1Rc3dDUVlEVlFRR0V3SlZVekFlRncweE5ERXdNall4TWpFd01UQmFGdzB4TmpFeE1qUXgKTWpFd01UQmFNSUdoTVM0d0xBWUtDWkltaVpQeUxHUUJBUXdlYldWeVkyaGhiblF1WTI5dExuTmxZWFJuWldWcgpMbE5sWVhSSFpXVnJNVFF3TWdZRFZRUUREQ3ROWlhKamFHRnVkQ0JKUkRvZ2JXVnlZMmhoYm5RdVkyOXRMbk5sCllYUm5aV1ZyTGxObFlYUkhaV1ZyTVJNd0VRWURWUVFMREFvNVFqTlJXVGxYUWxvMU1SY3dGUVlEVlFRS0RBNVQKWldGMFIyVmxheXdnU1c1akxqRUxNQWtHQTFVRUJoTUNWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQgpCd05DQUFRUGppQTFrVEVvZFNUMnd5NWQ1a1FGck0wRDVxQlg5VWtyeThXNkQrdkM3T3FiTW9UbS91cFJNMUdSCkhlQTJMYVZUcndBbnBHaG9PMEVUcVlGMk51NFZvNElDVlRDQ0FsRXdSd1lJS3dZQkJRVUhBUUVFT3pBNU1EY0cKQ0NzR0FRVUZCekFCaGl0b2RIUndPaTh2YjJOemNDNWhjSEJzWlM1amIyMHZiMk56Y0RBMExXRndjR3hsZDNkawpjbU5oTWpBeE1CMEdBMVVkRGdRV0JCUVdHZktnUGdWQlg4Sk92ODRxMWMwNEhTaE1tekFNQmdOVkhSTUJBZjhFCkFqQUFNQjhHQTFVZEl3UVlNQmFBRklTMmhNdzZobUp5RmxtVTZCcWp2VWpmT3Q4TE1JSUJIUVlEVlIwZ0JJSUIKRkRDQ0FSQXdnZ0VNQmdrcWhraUc5Mk5rQlFFd2dmNHdnY01HQ0NzR0FRVUZCd0lDTUlHMkRJR3pVbVZzYVdGdQpZMlVnYjI0Z2RHaHBjeUJqWlhKMGFXWnBZMkYwWlNCaWVTQmhibmtnY0dGeWRIa2dZWE56ZFcxbGN5QmhZMk5sCmNIUmhibU5sSUc5bUlIUm9aU0IwYUdWdUlHRndjR3hwWTJGaWJHVWdjM1JoYm1SaGNtUWdkR1Z5YlhNZ1lXNWsKSUdOdmJtUnBkR2x2Ym5NZ2IyWWdkWE5sTENCalpYSjBhV1pwWTJGMFpTQndiMnhwWTNrZ1lXNWtJR05sY25ScApabWxqWVhScGIyNGdjSEpoWTNScFkyVWdjM1JoZEdWdFpXNTBjeTR3TmdZSUt3WUJCUVVIQWdFV0ttaDBkSEE2Ckx5OTNkM2N1WVhCd2JHVXVZMjl0TDJObGNuUnBabWxqWVhSbFlYVjBhRzl5YVhSNUx6QTJCZ05WSFI4RUx6QXQKTUN1Z0thQW5oaVZvZEhSd09pOHZZM0pzTG1Gd2NHeGxMbU52YlM5aGNIQnNaWGQzWkhKallUSXVZM0pzTUE0RwpBMVVkRHdFQi93UUVBd0lES0RCUEJna3Foa2lHOTJOa0JpQUVRZ3hBUmprek9FWTBOalU0UTBFeVF6RkRPVU16Ck9FSTRSRVpEUWpWRVFrSXlRVEl5TkRVMk1EZEVSRVV5UmpFeE5EWXlNRVU0TkRZNFJVWTFNa1F5TURoRFFUQUsKQmdncWhrak9QUVFEQWdOSUFEQkZBaUIrUTR6enBNajJESlRDSWhERkJjbXdLMXpRQUM3MGZZMklzWWQ4K054dQp1d0loQUtqOVJyVE95aWFRbm9UNU1xaTNVSG9wYjZ4VHVnbDNMVURCbG9yYUJIeVAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
        - name: APPLE_PAY_PAYMENT_PROCESSING_PRIVATE_KEY
          value: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOqukXQoQVbg1xvvq/IGLdK0UuJPbbawULTALcuw/Uz2hRANCAAQPjiA1kTEodST2wy5d5kQFrM0D5qBX9Ukry8W6D+vC7OqbMoTm/upRM1GRHeA2LaVTrwAnpGhoO0ETqYF2Nu4V
        - name: AUTH_READ_TIMEOUT_SECONDS
          value: "1"
        - name: AWS_XRAY_CONTEXT_MISSING
          value: LOG_ERROR
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray:2000
        - name: CAPTURE_PROCESS_SCHEDULER_INITIAL_DELAY_SECONDS
          value: "0"
        - name: CAPTURE_PROCESS_SCHEDULER_RANDOM_INTERVAL_MAXIMUM_SECONDS
          value: "1"
        - name: CAPTURE_PROCESS_SCHEDULER_RANDOM_INTERVAL_MINIMUM_SECONDS
          value: "1"
        - name: CERTS_PATH
          value: /ssl/certs
        - name: DB_HOST
          value: {{ .Release.Name }}-postgresql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgresql-password
        - name: DB_USER
          value: connector
        - name: FRONTEND_URL
          value: http://frontend/
        - name: GDS_CONNECTOR_EPDQ_LIVE_URL
          value: http://stubs/stub/epdq
        - name: GDS_CONNECTOR_EPDQ_TEST_URL
          value: http://stubs/stub/epdq
        - name: GDS_CONNECTOR_SMARTPAY_LIVE_URL
          value: http://stubs/stub/smartpay
        - name: GDS_CONNECTOR_SMARTPAY_NOTIFICATION_PASSWORD
          value: smartpay-password
        - name: GDS_CONNECTOR_SMARTPAY_NOTIFICATION_USER
          value: smartpay-user
        - name: GDS_CONNECTOR_SMARTPAY_TEST_URL
          value: http://stubs/stub/smartpay
        - name: GDS_CONNECTOR_WORLDPAY_LIVE_URL
          value: http://stubs/stub/worldpay
        - name: GDS_CONNECTOR_WORLDPAY_TEST_URL
          value: http://stubs/stub/worldpay
        - name: JAVA_OPTS
          value: -Xms128m -Xmx1G
        - name: JPA_LOG_LEVEL
          value: WARNING
        - name: JPA_SQL_LOG_LEVEL
          value: WARNING
        - name: NOTIFY_API_KEY
          value: api_key-pay-notify-service-id-pay-notify-secret-needs-to-be-32-chars-fsghdngfhmhfkrgsfs
        - name: NOTIFY_BASE_URL
          value: http://stubs/notify
        - name: NOTIFY_EMAIL_ENABLED
          value: "true"
        - name: NOTIFY_PAYMENT_RECEIPT_EMAIL_TEMPLATE_ID
          value: email-template-id
        - name: NOTIFY_REFUND_ISSUED_EMAIL_TEMPLATE_ID
          value: email-refund-issued-template-id
        - name: RUN_APP
          value: "true"
        - name: RUN_MIGRATION
          value: "true"
        - name: SECURE_WORLDPAY_NOTIFICATION_DOMAIN
          value: pymnt.localdomain
        - name: SECURE_WORLDPAY_NOTIFICATION_ENABLED
          value: "false"
        - name: STRIPE_TRANSACTION_FEE_PERCENTAGE
          value: "0.1"
        - name: DB_SSL_OPTION
          value: "ssl=none"
        - name: CAPTURE_USING_SQS_FEATURE_FLAG
          value: "true"
        - name: AWS_SQS_REGION
          value: "region-1"
        - name: AWS_SQS_CAPTURE_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-capture-queue
              key: QueueURL
        - name: AWS_SQS_MESSAGE_MAXIMUM_WAIT_TIME_IN_SECONDS
          value: "20"
        - name: EVENT_QUEUE_ENABLED
          value: "true"
        - name: AWS_SQS_PAYMENT_EVENT_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-event-queue
              key: QueueURL
        - name: EMIT_PAYMENT_STATE_TRANSITION_EVENTS
          value: "true"
        resources: {}
        ports:
          - name: app
            containerPort: 80
          - name: admin
            containerPort: 8081
      restartPolicy: Always
